### PR TITLE
Final changes from my side

### PR DESCRIPTION
**Pull request by nuest**
- [x] fix figure caption formatting
- [x] add Listing 6 as example
- [x] archive to Zenodo, to preserve the examples
- [x] make Listing 1 a working Dockerfile, although still not "sensible"
- [x] use other listing formatting so the listings don't break across pages

### CODE REVIEW

**Comment by nuest** [comment]
@sje30 What do you think about this "working" Dockerfile as the full example.

@vsoch Stephen suggested to make the "full Dockerfile" one that actually works, and here is my attempt at doing that.

**Comment by sje30** [comment]
> What do you think about this "working" Dockerfile as the full example.

I think it looks good.  But shouldn't it also be available in the examples folder so that someone can run it.  (Listings legend should then say how it should be run.)

**Comment by sje30** [comment]
or even if it just on dockerhub, so that someone can run it with a command that we give them.

**Comment by nuest** [comment]
It is in the examples directory, see https://github.com/nuest/ten-simple-rules-dockerfiles/blob/ab5d300ea986ac924f8b985d2ed27905189381a7/examples/full-demo/Dockerfile

It is included into the manuscript form that file, see https://github.com/nuest/ten-simple-rules-dockerfiles/pull/81/files#diff-a5e29fb9dc2e9e18941d1125cabcbaefR158

Re. build on Docker Hub: IMO we want people to look at the Dockerfile to better understand the application of the rules. Having a pre-built image does not add a value to that. But I can of course create an automated build on Docker Hub and Circle CI :-)

**Comment by nuest** [comment]
I merge this now and then create an automated build on Docker Hub and Quay.io.

**Pull request merged**
