### PR TITLE
Add source code and tweak executable label

### PR DESCRIPTION
**Pull request by bdevans**
This addresses #71 and makes the terminology for the executable consistent. 

The image was generated with drawio - a free web-based vector drawing program: https://app.diagrams.net/

### CODE REVIEW

**Comment by vsoch** [comment]
I still love this figure! One small nit, if you happen to open it in the graphics editor again. The border around the right figure arrows is a dark orange, which matches the arrows gradient and also isn't distracting to be under the text. The same border for the left arrows (which are blue) is in black, and it's a little distracting for the text on top of it. So if you are able, we might consider having the border around the left blue arrows also be a darker blue - both to match the other set of arrows and make the text easy to read.

**Comment by nuest** [comment]
Thanks @bdevans ! I'll leave this open for now since I hope you address the comments by @vsoch.

**Comment by bdevans** [comment]
Good spot @vsoch! I've made the colour scheme consistent now. I also tweaked the names of the example files but am open to other ideas e.g. "model.c" and "project" or perhaps also "model" for the docker image.

**Comment by vsoch** [comment]
Perfecto! Here is the graphic for others to easily see:
image

I think the names "my*" are ok, it is simple and directly tells the user "This is a custom thing you are creating, not some idea of "model" or "project" that you don't know about."

**Comment by bdevans** [comment]
> Perfecto! Here is the graphic for others to easily see:

Almost - I recently edited it to say `myprog.c` for consistency.

**Comment by nuest** [comment]
Thanks @bdevans I support the "my"-names, they fit well with the general tone of the article.

**Pull request merged**
