### PR TITLE
Ben's edits to the text

### PR DESCRIPTION
**Pull request by benmarwick**
Thanks for your nudge. I've made a bunch of small edits to the text. What do you think?

### CODE REVIEW

**Comment by nuest** [comment]
Thanks Ben, this is very helpful!

Do you have any comments about the _big picture_ (motivation reasonable, scope useful, layout of the rules understandable, rule content wise) or level of detail? IMO it's time for some reshaping and cutting things to keep the rules "simple" (enough).

**Comment by benmarwick** [comment]
Sure, I found the rules 'Pin versions',  'Bind mount data and control code', 'Capture structured environment metadata', to be challenging to understand. 

I guess this might be because of the terminology, for example, 'pin', 'bind' and 'capture' are verbs that will not be clearly understood by researchers outside of computer science and dev-ops roles. If these and other similar technical terms could be replaced with plain-English descriptions, that would be a general big-picture improvement overall, to make it easier for regular scientists to engage with containers. Another general idea is defining technical terms in their first mention. 

Many of the LABEL standards were new to me, and I've not seen them in the wild at all. Are they in common use, or is this aspirational? I think we want to focus on what we know to be common practices here. The rocker project is using  org.label-schema.* is that the same as what is mentioned here?

For binding data I think that rule is currently not a good fit with the role of containers as reproducible compendia that capture as much as possible. Perhaps that rule could be re-written to be more of a guide to the user about when to bind and when not?

Hope that helps!

**Comment by vsoch** [comment]
Definitely agree - here are some suggestion:

- Pin versions: Use containers tagged with version numbers for reproducible builds
- Bind mount data and control code: Bring data into isolated containers by mounting volumes
- Capture structured environment metadata: Use build arguments to customize builds

Of course those can be further worked on, there are still a lot of developer type words in there :)

For labels, you also see a similar namespace of labels with GitHub actions, e.g. https://github.com/Azure/github-actions/blob/master/functionscontainer/Dockerfile and Singularity containers:

```bash
singularity exec sregistry-cli singularity inspect --json sregistry-cli
{
    "data": {
        "attributes": {
            "labels": {
                "org.label-schema.usage.singularity.deffile.bootstrap": "docker",
                "MAINTAINER": "vsochat@stanford.edu",
                "org.label-schema.usage.singularity.deffile": "Singularity",
                "org.label-schema.schema-version": "1.0",
                "org.label-schema.usage.singularity.deffile.from": "continuumio/miniconda3",
                "org.label-schema.build-date": "Mon,_08_Jan_2018_12:54:52_-0800",
                "org.label-schema.usage.singularity.version": "2.4.1-bleuchien-apprunfix.g85c133d",
                "org.label-schema.build-size": "861MB"
            }
        },
        "type": "container"
    }
}
```

I agree about binding data as well - we might mention that the role of the container is not to provide large data, but the methods to run over it. For testing it's good practice to include some dummy data within the container to ensure that it can continue to be parsed as expected. If the container can successfully still process the testing data, we can then infer that (it's more likely) our larger custom data bound at runtime will be processed correctly.

**Comment by nuest** [comment]
- Re. _pin versions_: I went for explaning the term, because I think reader's should understand it when they see it (later in the text or in the wild), but also changed the rule name (included in https://github.com/nuest/ten-simple-rules-dockerfiles/commit/c948e90b9803f4047b716d03332e5a2733d527f7)
- Re. _bind mount data..._: Rule name updated, and also tried to incorporate your thoughts in the rule, though probably the rule does _not_ follow @benmarwick 's idea to capture "as much as possible", but goes into the direction of "what to add and what not". **I don't know when it would be reasonable to `COPY` data into a container, IMO: never. Hope the rule works better now: https://github.com/nuest/ten-simple-rules-dockerfiles/commit/e29e933d6b2760f7537b07653a5de41995bb3acd
- Re. _labels_: `org.label-schema.*` is "deprecated" you could say, but more widely used still: http://label-schema.org/rc1/ - I have explained it in the text now. _Do you think we should stick to the more commonly used ones?_

Feedback welcome!

**Comment by vsoch** [comment]
The pinning versions comment is good - and when I think about it, pinning versions in a container is very different from pinning on your host. On your host, you already have stuffs installed, and so saying a version must be == can actually lead to incompatibility pretty quickly. But if you essentially freeze a set of versions via a container, unless some hidden dependency is changed, you should be okay. I've run into trouble, for example, pinning versions of something that requires matplotlib, but then a newer version is installed that (for some reason) doesn't work with a function. I guess it's one of those "best effort" situations - you can't be perfect, but you can do your best.
 
I disagree with this comment to some extent:

> It is better to insert data files and scripts files from the local machine into the container at run time, and using the container image primarily for the software and dependencies.

Scripts and small data files that are core to the tool are essential to add to the container. If someone wants to run a container that is expected to do X, they shouldn't be expected to provide the main script that uses the software to do X. The distinction that is missing here for me is:

 - some containers might be intended to serve as environments. Data/scripts should be mounted at runtime for these containers
 - other containers are complete encapsulated workflows. While very large data might need to be mounted at runtime, the core software should be added with COPY.

As it is now, to a large subset of container community it will just read wrong, so the clarification is needed. I would rework this entire section because as I read it, I feel strong sentiment of "no this isn't right..."

For the labels schema, I think it's okay to mention that it's widely used, however the direction is to superceded them (see here https://github.com/opencontainers/image-spec/blob/master/annotations.md)

**Pull request merged**
