### PR TITLE
Summary and revised figure

### PR DESCRIPTION
**Pull request by bdevans**
This addresses #62, adding a summary figure of the rules, reformats the analogy figure for a consistent aesthetic and makes some associated minor changes to the text. 

Hopefully this is the final PR before submission!

### CODE REVIEW

**Comment by bdevans** [comment]
As mentioned, the only other change I would propose (not yet committed) is to rename Rule 2 to "Build on available images" (of which using versioned images is a natural sub-rule). The generality of the new wording would follow well from Rule 1 as they are both encouraging readers to not reinvent the wheel.

**Comment by nuest** [comment]
@bdevans Renaming Rule 2 is a good idea, I like the distinction between "use" and "build", too.  Please go ahead and make that change, then we can merge and I'll submit after pinging the remaining coauthors again.

**Comment by bdevans** [comment]
Hi @nuest, I've made the changes and slightly reworked (mostly reordered) the text for Rule 2 for a more natural flow (it might be easiest to follow from the sequence of commits rather than the aggregated changes). I've also fixed a couple of minor typos and inconsistencies. 

Hopefully this is now good to go! 🚀

**Comment by nuest** [comment]
Good work - I am glad you discovered (the hopefully final ones) and fixed some container/image mixups.

**Pull request merged**
